printWidth: 80
useTabs: true
semi: true
singleQuote: true
trailingComma: 'all'
bracketSpacing: true
arrowParens: 'always'
htmlWhitespaceSensitivity: 'css'
endOfLine: 'lf'
singleAttributePerLine: true
