[build]
  publish = "_site"
  command = "npm run build"
[[headers]]
  for = "/fonts/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
[[redirects]]
  from = "https://email.mail.sayansivakumaran.com/*"
  to = "https://mailgun.org"
  status = 301 
  force = true
