name: accessibility tests

on: [deployment_status]

jobs:
  build:
    name: Build site and run pa11y-ci tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install NPM dependencies
      run: npm install

    - name: Build eleventy and run pa11y-ci
      run: npm run test:pa11y-ci