name: HTML Validation and Accessibility Tests

on: [push]

env:
  ELEVENTY_ENV: development

jobs:
  build:
    name: Build site and run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install NPM dependencies
        run: npm install

      - name: Build eleventy and run pa11y-ci
        run: npm run test:pa11y-ci

      - name: Run Nu validator
        run: java -jar node_modules/vnu-jar/build/dist/vnu.jar --skip-non-html --Werror --verbose _site
